services:
  postgres:
    image: postgres:17.5-bookworm
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./init_db.py:/docker-entrypoint-initdb.d/init_db.py
      - ./schema_star.sql:/schema_star.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  etl:
    image: python:3.11.12-bookworm
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./etl:/app
      - ./init_db.py:/app/init_db.py
      - ./schema_star.sql:/app/schema_star.sql
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install -r requirements.txt && python init_db.py && python etl_ida.py"

  docs:
    image: python:3.11.12-bookworm
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./docs:/docs
    working_dir: /app
    ports:
      - "8756:8080"
    restart: unless-stopped
    command: >
      sh -c "\
        pip install -r requirements.txt && \
        python -m pydoc -w etl.etl_ida init_db && \
        mv etl.etl_ida.html /docs/etl_ida.html && \
        mv init_db.html /docs/init_db.html && \
        cd /docs && \
        python -m http.server 8080\
      "
