services:
  postgres:
    image: postgres:17.5-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: idadatamart
    volumes:
      - ./init_db.py:/docker-entrypoint-initdb.d/init_db.py
      - ./schema_star.sql:/schema_star.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - "5432:5432"

  etl:
    image: python:3.11.12-bookworm
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./etl-ida-sysint.py:/app/etl-ida-sysint.py
      - ./init_db.py:/app/init_db.py
      - ./requirements.txt:/app/requirements.txt
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install -r requirements.txt && python init_db.py && python etl-ida-sysint.py"
